---
# code: language=yaml
name: Site deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    container:
      image: ghcr.io/elastic/mkdocs-material-insiders-ia:elastic-ia
      credentials:
        username: ${{ secrets.CUSTOM_GHCR_USERNAME}}
        password: ${{ secrets.CUSTOM_GHCR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare for build
        run: |
          python setup.py install
          rm -rf ./site/*

      - name: Run build command
        run: mkdocs build --config-file mkdocs.insiders.yml
        env:
          GA_PROPERTY_ID: ${{ secrets.GA_PROPERTY_ID }}
          MKDOCS_ENABLE_RSS_PLUGIN: "True"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
